- name: ensure cinder packages are installed
  apt: name={{ item }} 
  with_items:
    - cinder-api 
    - cinder-scheduler
    - python-cinderclient

- name: ensure cinder sqlite is deleted
  file: dest=/var/lib/cinder/glance.sqlite state=absent

- name: register internal IP
  shell: "ip a show dev {{ int_net_nic }}|grep inet|grep -v inet6|awk '{print $2}'|cut -d/ -f1"
  register: internal_ip_address

- name: ensure cinder.conf is configured
  template: >
    src=etc/cinder/cinder.conf
    dest=/etc/cinder/cinder.conf
    owner=cinder group=cinder mode=0640
  notify:
    - restart cinder services

- name: ensure cinder db is initialized
  command: /usr/bin/cinder-manage db sync
  notify: restart cinder services
