- name: ensure br-int switch is created
  openvswitch_bridge: bridge=br-int state=present
  notify: restart ovs agent
  
- name: ensure br-ex switch is created
  openvswitch_bridge: bridge=br-ex state=present
  notify: restart ovs agent

- name: ensure br-ex_setup.sh script is copied to the network-node
  template: >-
    src=root/br-ex_setup.sh
    dest=/root/br-ex_setup.sh
    owner=root
    group=root
    mode=750

- name: ensure external interface is properly configured
  command: /root/br-ex_setup.sh
  
# # From /usr/share/doc/neutron-common
# - name: ensure br-ex is set as an external bridge
#   command: ovs-vsctl br-set-external-id br-ex bridge-id br-ex

# - name: Ensure default route is deleted
#   command: /sbin/ip route del default
#   ignore_errors: True
  
# - name: ensure IP address is deleted from external nic
#   command: /sbin/ip addr del {{ network_node_external_ip }}/{{ network_node_external_CIDR }} dev {{ ext_net_nic }}
#   ignore_errors: True

# - name: ensure br-ex is up
#   command: /sbin/ip link set br-ex up
  
# - name: ensure external interface is added to br-ex
#   openvswitch_port: bridge=br-ex port={{ ext_net_nic }} state=present
#   notify: restart neutron agents
#   ignore_errors: True

# - name: ensure IP address is added to external bridge
#   command: /sbin/ip addr add {{ network_node_external_ip }}/{{ network_node_external_CIDR }} dev br-ex
#   ignore_errors: True

# - name: ensure default rule is associated to external bridge
#   command: /sbin/ip route add default via {{ external_gateway }}
#   ignore_errors: True
  
- name: ensure br-ex is configured and external interface added permanently
  template: >-
    src=etc/network/interfaces
    dest=/etc/network/interfaces
    owner=root group=root mode=0644


