- name: verify if hypervisor support hw accel is enabled
  command: egrep '(vmx|svm)' /proc/cpuinfo
  register: result
  ignore_errors: True

- name: ensure nova-compute-kvm is installed when hw accel is enabled
  apt: name=nova-compute-kvm 
  when: result|success

- name: ensure nova-compute-qemu is installed when hw accel is not enabled
  apt: name=nova-compute-qemu 
  when: result|failed

- name: ensure python-guestfs and sysfsutils are installed
  apt: name={{item}} 
  with_items:
    - python-guestfs
    - sysfsutils
  
- name: ensure nova sqlite is deleted
  file: dest=/var/lib/nova/nova.sqlite state=absent
    
- name: ensure nova.conf file is present
  template: >
    src=../../novaserver/templates/etc/nova/nova.conf
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0660
  notify: 
  - restart nova-compute

