- name: ensure neutron server and neutron-plugin-ml2 are installed
  apt: name={{ item }} 
  with_items:
    - neutron-server
    - neutron-common
    - neutron-plugin-ml2
    - python-neutronclient

- name: ensure neutron.conf is configured
  template: >
    src=etc/neutron/neutron.conf
    dest=/etc/neutron/neutron.conf
    owner=neutron group=neutron mode=0660
  notify:
    - restart neutron-server

- name: ensure ml2 plugin is configured
  template: >
    src=etc/neutron/plugins/ml2/ml2_conf.ini
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root group=root mode=0644
  notify:
    - restart neutron-server

- name: ensure neutron db is initialized
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  notify:
    - restart neutron-server

- name: ensure neutron sqlite is deleted
  file: dest=/var/lib/neutron/neutron.sqlite state=absent
    