- name: ensure apache and memcached packages are installed
  apt: name={{ item }} 
  with_items:
    - memcached
    - apache2
    - libapache2-mod-wsgi
    
- name: ensure horizon packages are installed 
  apt: name={{ item }}  
  with_items:
    - python-django-horizon
    - openstack-dashboard
    
- name: ensure dashboard is configured
  template: >
    src=etc/openstack-dashboard/local_settings.py
    dest=/etc/openstack-dashboard/local_settings.py
    owner=root group=root mode=0644
  notify: restart web services

- name: ensure ubuntu horizon theme is deinstalled
  command: apt-get -y remove --auto-remove openstack-dashboard-ubuntu-theme
  
# - name: ensure default virtualhost is disabled
#   command: a2dissite {{ item }}
#   with_items:
#     - 000-default
#     - default-ssl
#     - openstack-dashboard-alias-only
    
#   notify: restart web services

# - name: ensure openstack-dashboard-ssl virtualhost is enabled
#   command: a2ensite {{ item }}
#   with_items:
#     - openstack-dashboard-ssl
#     - openstack-dashboard-ssl-redirect
    
#   notify: restart web services
  
- name: ensure ssl, wsgi and rewrite modules are enabled
  apache2_module: name={{ item }} state=present
  with_items:
    - wsgi
    - ssl
    - rewrite
  notify: restart web services